apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-hp
  namespace: sample-domain2-ns
spec:
  storageClassName: jenkins-pv-hp
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/rbajaj/Documents/weblogic-poc/weblogic-cicd-domain-home-in-image/temp