apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-hostpath
  namespace: sample-domain2-ns
spec:
  storageClassName: jenkins-pv-hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/rbajaj/jenkinspoddata